name: Train Heart Disease Model CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Workflow-CI
    steps:
      - name: Set up job
        run: echo "Starting CI pipeline for Heart Disease Model"

      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Check Env
        run: |
          python --version
          pip --version
          which python

      - name: Install dependencies
        run: |
          pip install mlflow scikit-learn pandas numpy

      - name: Run mlflow project
        run: |
          mlflow run MLProject --no-conda

      - name: Get latest MLflow run_id
        run: |
          python -c "import mlflow; client=mlflow.tracking.MlflowClient(); exp=client.get_experiment_by_name('Heart_Disease_CI'); runs=client.search_runs(exp.experiment_id, order_by=['start_time DESC'], max_results=1) if exp else []; print(f'Run ID: {runs[0].info.run_id}') if runs else print('No runs found')"
